repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
        files: ^evasion/.*$
    -   id: trailing-whitespace
        files: ^evasion/.*$
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        files: ^evasion/.*\.py$
